import { ALLCATEGORY, SIGNIN } from './query'
import { ONCHANGECATEGORY } from './subscription'
import { NEWCATEGORY, UPDATECATEGORY, DELETECATEGORY } from './mutation'
export {
    SIGNIN,
    ALLCATEGORY,
    ONCHANGECATEGORY,
    NEWCATEGORY,
    UPDATECATEGORY,
    DELETECATEGORY
}
